# Generated by Django 3.2.13 on 2022-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='pk')),
                ('login_id', models.CharField(max_length=15, verbose_name='이름')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='전화번호')),
            ],
        ),
    ]
